---
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
            - vars/var.yml          

  roles:
          - bastion-host
          - private-instance
          
          

