---
- hosts: webserver
  become: true
  vars:
          http_port: 8000
          https_port: 4443
          html_welcome_msg: "hello laurel"
  tasks: 
  #this is a task to install apache to the latest version
          - name: install apache server
            apt:
                    name:
                            -  apache2
                            -  libapache2-mod-php
                    state: latest

                    # set timezone of server to africa lagos
          - name: set timezone
            timezone:
                   name: Africa/Lagos

# host index.php file on apache and change permission to 644                                        
          - name: host php file
            tags: apache2
            copy:
                   src: index.php
                   dest: /var/www/html/
                   mode: 0644
