---

- name: Install Nginx
  apt:
          name: nginx
          state: latest
  tags: nginx


- name: create www document root directory
  become: true
  file:
          path: "/var/www/{{ http_host }}"
          state: directory
          mode: '0775'
          owner: www-data
          group: www-data
          recurse: yes
  tags: nginx
         

- name: delete default nginx site
  file:
          path: /etc/nginx/sites-available/default
          state: absent

- name: delete default nginx site
  file:
          path: /etc/nginx/sites-enabled/default
          state: absent

- name: copy project directory to site
  template:
          src: /project
          dest: /var/www/
          mode: '0755'
          owner: "{{ app_user }}"
          group: "{{ app_user }}"
  tags: nginx

- name: copy nginx site.conf
  template:
          src: site.conf
          dest: /etc/nginx/sites-available/
          owner: root
          group: root
          mode: '0644'

- name: enable new conf
  become: true
  shell: ln -s /etc/nginx/sites-available/site.conf /etc/nginx/sites-enabled/
  notify:
          - nginx service started
          - nginx service enabled          
